# Generated by Django 5.0.6 on 2024-05-27 09:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Myproduct', '0002_productadminmodel'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='product',
            options={'permissions': [('can_view_product', 'Can view product')]},
        ),
    ]
